name: Expando
version: '${project.version}'
main: com.github.molkars.expando.Expando
api-version: 1.17
authors: [ Molkars ]
commands:
  expando:
    description: Start the border
    permission-message: No perms
    usage: |
      expando <sub-command>

      Available Subcommands:
        start <radius> | Start the world border
        status         | The status of current group/world you are in (kill counts, size)
    subcommands:
